/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectoCerveza.Grano;
import proyectoCerveza.Receta;
import CRUD.crudGeneralCEM;

import java.util.List;

/**
 *
 * @author ADM
 */
public class InterfazGrano extends javax.swing.JFrame {
    
    private crudGeneralCEM operacionesCRUD = new crudGeneralCEM();
    
    public InterfazGrano() throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        tblGrano.setModel(operacionesCRUD.opBuscar("Grano", "", ""));
    }
    
    public void limpiarGrano(){
        txtGrano.setText("");
        txtProcedencia.setText("");
    }
    
    public void activarGrano(boolean activado){
        btnRegistrar.setEnabled(activado);
        txtGrano.setEnabled(activado);
        txtProcedencia.setEnabled(activado);
        txtBusquedaGrano.setEnabled(!activado);
    }
    
    public void mensajeAdvertencia(String mensaje, String titulo){
        JOptionPane.showMessageDialog(null,mensaje,titulo,0);
    }
    public void mensajeInformativo(String mensaje, String titulo){
        JOptionPane.showInternalMessageDialog(null, mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
    }
    
    
    public boolean validarDatos(){
        // Validación del código de la cerveza
        if (txtGrano.getText().equals("") || 
                txtGrano.getText().equals("Ingrese el grano")) {
            mensajeAdvertencia("El grano es inválido.\n"
                    + "Favor de verificar que:\n"
                    + "-> No contenga acentos\n"
                    + "-> No contenga caracteres especiales\n"
                    + "-> Haya registrado correctamente el grano\n", "Grano inválido");
            return false;
        }
        if (txtProcedencia.getText().equals("") || 
                txtGrano.getText().equals("Ingrese la procedencia")) {
            mensajeAdvertencia("Procedencia invalida.\n"
                    + "Favor de verificar que:\n"
                    + "-> No contenga acentos\n"
                    + "-> No contenga caracteres especiales\n"
                    + "-> Haya registrado correctamente la procedencia\n", "Procedencia invalida");
            return false;
        }
       
        return true;
    }
    
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosEnvase = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtGrano = new javax.swing.JTextField();
        txtProcedencia = new javax.swing.JTextField();
        lblCapacidad = new javax.swing.JLabel();
        btnCancelarEnvase = new javax.swing.JButton();
        btnNewEnvase = new javax.swing.JButton();
        pnlRegistrros = new javax.swing.JPanel();
        lblBusqueda = new javax.swing.JLabel();
        txtBusquedaGrano = new javax.swing.JTextField();
        lblAtributo = new javax.swing.JLabel();
        cmbAtributos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrano = new javax.swing.JTable();
        btnInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlDatosEnvase.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Grano"));
        pnlDatosEnvase.setEnabled(false);

        lblTipo.setText("Grano:");
        lblTipo.setEnabled(false);

        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.setEnabled(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.setEnabled(false);
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar Campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtGrano.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGrano.setText("Ingrese el nombre del grano");
        txtGrano.setEnabled(false);

        txtProcedencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProcedencia.setText("Ingrese la procedencia del grano");
        txtProcedencia.setEnabled(false);
        txtProcedencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcedenciaActionPerformed(evt);
            }
        });

        lblCapacidad.setText("Procedencia:");
        lblCapacidad.setEnabled(false);

        javax.swing.GroupLayout pnlDatosEnvaseLayout = new javax.swing.GroupLayout(pnlDatosEnvase);
        pnlDatosEnvase.setLayout(pnlDatosEnvaseLayout);
        pnlDatosEnvaseLayout.setHorizontalGroup(
            pnlDatosEnvaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosEnvaseLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlDatosEnvaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosEnvaseLayout.createSequentialGroup()
                        .addComponent(btnLimpiar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlDatosEnvaseLayout.createSequentialGroup()
                        .addGroup(pnlDatosEnvaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTipo)
                            .addComponent(lblCapacidad))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDatosEnvaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProcedencia)
                            .addComponent(txtGrano))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(pnlDatosEnvaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addContainerGap(39, Short.MAX_VALUE))))
        );
        pnlDatosEnvaseLayout.setVerticalGroup(
            pnlDatosEnvaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosEnvaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(btn_Eliminar)
                .addGap(61, 61, 61))
            .addGroup(pnlDatosEnvaseLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlDatosEnvaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(txtGrano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosEnvaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapacidad)
                    .addComponent(txtProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelarEnvase.setText("Cancelar");
        btnCancelarEnvase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEnvaseActionPerformed(evt);
            }
        });

        btnNewEnvase.setText("Nuevo Grano");
        btnNewEnvase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewEnvaseActionPerformed(evt);
            }
        });

        pnlRegistrros.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registros Grano"));

        lblBusqueda.setText("Búsqueda");

        txtBusquedaGrano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaGranoKeyReleased(evt);
            }
        });

        lblAtributo.setText("Atributo:");

        cmbAtributos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grano", "Procedencia" }));

        tblGrano.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tblGrano);

        javax.swing.GroupLayout pnlRegistrrosLayout = new javax.swing.GroupLayout(pnlRegistrros);
        pnlRegistrros.setLayout(pnlRegistrrosLayout);
        pnlRegistrrosLayout.setHorizontalGroup(
            pnlRegistrrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusquedaGrano, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAtributo)
                .addGap(18, 18, 18)
                .addComponent(cmbAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        pnlRegistrrosLayout.setVerticalGroup(
            pnlRegistrrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistrrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusquedaGrano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAtributo)
                    .addComponent(cmbAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBusqueda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnInicio.setText("Regresar al Menu");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelarEnvase)
                        .addGap(27, 27, 27)
                        .addComponent(btnNewEnvase))
                    .addComponent(pnlDatosEnvase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRegistrros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 484, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDatosEnvase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarEnvase)
                    .addComponent(btnNewEnvase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRegistrros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarEnvaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEnvaseActionPerformed
        btnNewEnvase.setEnabled(true);
        tblGrano.clearSelection(); 
    }//GEN-LAST:event_btnCancelarEnvaseActionPerformed

    private void btnNewEnvaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewEnvaseActionPerformed
        limpiarGrano();
        activarGrano(true);
        
    }//GEN-LAST:event_btnNewEnvaseActionPerformed

    private void txtBusquedaGranoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaGranoKeyReleased
    
        
    }//GEN-LAST:event_txtBusquedaGranoKeyReleased

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
    try{
           Home inicio = new Home();
            inicio.setVisible(true);
            // Cerrar la ventana
            dispose();  
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ocurrió un error",
                    "Error",0);

        }
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarGrano();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed

    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if(validarDatos()) {
            try {
                // Verificar si el grano fue encontrado
                int id = operacionesCRUD.opMaxID("Grano") + 1;
                Grano nuevoGrano = new Grano(id, txtGrano.getText(), txtProcedencia.getText());

                operacionesCRUD.opPersistObjeto("Grano", nuevoGrano);
                System.out.println("Grano registrado exitosamente.");

            }catch (Exception err) {
                err.printStackTrace(); // Muestra el error completo en la consola para diagnóstico
                JOptionPane.showMessageDialog(null, "Los datos introducidos no son válidos",
                        "Error al registrar la receta",
                        JOptionPane.ERROR_MESSAGE);
            }

        } else {
            mensajeAdvertencia("Registro no realizado", "Error de captura de datos");
        }

        limpiarGrano();
        activarGrano(false);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtProcedenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcedenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProcedenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazGrano().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(InterfazGrano.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelarEnvase;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNewEnvase;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JComboBox<String> cmbAtributos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtributo;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel pnlDatosEnvase;
    private javax.swing.JPanel pnlRegistrros;
    private javax.swing.JTable tblGrano;
    private javax.swing.JTextField txtBusquedaGrano;
    private javax.swing.JTextField txtGrano;
    private javax.swing.JTextField txtProcedencia;
    // End of variables declaration//GEN-END:variables
}
